

// / FIREBASE AUTH ACTIONS
export const FIREBASE_REF_TOWN = 'FIREBASE_REF_TOWN';
export const FIREBASE_REF_RATING = 'FIREBASE_REF_RATING';
export const SET_CUR_STATE = 'SET_CUR_STATE';
export const SET_CUR_TOWN = 'SET_CUR_TOWN';